# Generated by Django 5.2.8 on 2025-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('ENGLSIH', 'ENGLISH'), ('HINDI', 'HINDI'), ('MARATHI', 'MARATHI')], default='ENGLISH', max_length=20),
        ),
    ]
