# Generated by Django 5.2.8 on 2025-12-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('HINDI', 'HINDI'), ('MARATHI', 'MARATHI')], default='ENGLISH', max_length=20),
        ),
    ]
