# Generated by Django 5.2.8 on 2025-12-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
